version: '3'
services:
    mysql:
        image: 'mysql'
        command: --init-file /data/application/mysql.sql --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '5306:3306'
        environment:
            MYSQL_DATABASE: 'test_db'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                'CMD',
                '/usr/bin/mysql',
                '-hlocalhost',
                '-ulupdo',
                '-plupdo@s3cRet',
                '-e',
                'SELECT 1',
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always
        volumes:
            - 'lupdo-mysql:/var/lib/mysql'
            - ./src/__tests__/data/mysql.sql:/data/application/mysql.sql
    waitmysql:
        image: 'mysql'
        links:
            - mysql
        depends_on:
            - mysql
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmariadb -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'
    mariadb:
        image: 'mariadb:10'
        command: --init-file /data/application/mysql.sql --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
        ports:
            - '5308:3306'
        environment:
            MYSQL_DATABASE: 'test_db'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "lupdo"
            MYSQL_PASSWORD: "lupdo@s3cRet"
        healthcheck:
            test:
                [
                'CMD',
                '/usr/bin/mysql',
                '-hlocalhost',
                '-ulupdo',
                '-plupdo@s3cRet',
                '-e',
                'SELECT 1',
                ]
            interval: 30s
            timeout: 5s
            retries: 3
        restart: always
        volumes:
            - 'lupdo-mariadb:/var/lib/mysql'
            - ./src/__tests__/data/mysql.sql:/data/application/mysql.sql

    waitmariadb:
        image: 'mariadb:10'
        links:
            - mariadb
        depends_on:
            - mariadb
        entrypoint:
            - bash
            - -c
            - 'until /usr/bin/mysql -hmariadb -ulupdo -plupdo@s3cRet -e "SELECT 1"; do sleep 5; done'

    # pgsql:
    #     image: 'postgres:14'
    #     command: '-c full_page_writes=off -c fsync=off -c synchronous_commit=off'
    #     ports:
    #         - '5307:5432'
    #     environment:
    #         POSTGRES_DB: 'test_db'
    #         POSTGRES_USER: 'lupdo'
    #         POSTGRES_PASSWORD: 'lupdo@s3cRet'
    # waitpgsql:
    #     image: 'postgres:14'
    #     links:
    #         - pgsql
    #     depends_on:
    #         - pgsql
    #     entrypoint:
    #         - bash
    #         - -c
    #         - 'until /usr/local/bin/psql postgres://lupdo:lupdo@postgres/test_db -c "SELECT 1"; do sleep 5; done'

volumes:
    lupdo-mysql:
        driver_opts:
            type: tmpfs
            device: tmpfs
    lupdo-mariadb:
        driver_opts:
            type: tmpfs
            device: tmpfs
