export const users = [
    ['Edmund', 'Multigender'],
    ['Kyleigh', 'Cis man'],
    ['Josefa', 'Cisgender male'],
    ['Cecile', 'Agender'],
    ['Sincere', 'Demi-girl'],
    ['Baron', 'Cisgender male'],
    ['Mckayla', 'Genderflux'],
    ['Wellington', 'Cisgender woman'],
    ['Tod', 'Demi-man'],
    ['Jeffrey', 'Androgyne'],
    ['Keenan', 'Two-spirit person'],
    ['Lucile', 'Man'],
    ['Kyra', 'Other'],
    ['Jermain', 'Gender neutral'],
    ['Kelli', 'Agender'],
    ['Jeffry', 'Two-spirit person'],
    ['Dawn', 'Male to female'],
    ['Ofelia', 'Cis female'],
    ['Icie', 'F2M'],
    ['Matilde', 'Trans'],
    ['Marcelina', 'Transgender female'],
    ['Destin', 'Male to female transsexual woman'],
    ['Reilly', 'Intersex man'],
    ['Casimer', 'Other'],
    ['Carli', 'Bigender'],
    ['Harry', 'Cis man'],
    ['Ellie', 'Omnigender'],
    ['Solon', 'Gender neutral'],
    ['Lesley', 'Cis'],
    ['Nikolas', 'Agender']
];
export const companies = [
    ['Satterfield Inc'],
    ['Grimes - Reinger'],
    ['Skiles LLC'],
    ['White, Hermiston and Kihn'],
    ['Huel LLC'],
    ['Aufderhar - Schroeder'],
    ['Powlowski - VonRueden'],
    ['Murray - Hagenes'],
    ['Bednar LLC'],
    ['Kirlin - Bednar'],
    ['Kassulke - Auer'],
    ['Orn - Pouros'],
    ['Greenfelder - Paucek'],
    ['Hand, Effertz and Shields'],
    ['Harber - Heidenreich'],
    ['Greenholt - Durgan'],
    ['Hauck - Murazik'],
    ['Beier and Sons'],
    ['Harvey Inc']
];
